DROP SCHEMA IF EXISTS TechSolution;

CREATE SCHEMA TechSolution;

USE TechSolution;

CREATE TABLE IF NOT EXISTS CLIENTES (
    CODIGO INT PRIMARY KEY,
    CNPJ VARCHAR(14) NOT NULL UNIQUE,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    RAMO_ATIVIDADE VARCHAR(50),
    DATA_CADASTRAMENTO DATE,
    PESSOA_CONTATO VARCHAR(100)
);

ALTER TABLE CLIENTES ADD COLUMN TELEFONES TEXT; -- Multivalorado
ALTER TABLE CLIENTES ADD COLUMN ENDERECOS TEXT; -- Multivalorado
ALTER TABLE CLIENTES DROP COLUMN PESSOA_CONTATO;

CREATE TABLE IF NOT EXISTS EMPREGADOS (
    MATRÍCULA INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CARGO VARCHAR(50),
    SALARIO DECIMAL(10, 2),
    DATA_ADMISSAO DATE,
    QUALIFICACOES TEXT,
    ENDERECO TEXT
);

ALTER TABLE EMPREGADOS ADD COLUMN TELEFONES TEXT; -- Multivalorado
ALTER TABLE EMPREGADOS DROP COLUMN ENDERECO;

CREATE TABLE IF NOT EXISTS EMPRESAS (
    CNPJ VARCHAR(14) PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    PESSOA_CONTATO VARCHAR(100)
);

ALTER TABLE EMPRESAS ADD COLUMN TELEFONES TEXT; -- Multivalorado
ALTER TABLE EMPRESAS ADD COLUMN ENDERECO TEXT; 

-- Criar a tabela FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES (
    CNPJ VARCHAR(14) PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    PESSOA_CONTATO VARCHAR(100),
    ENDERECO TEXT
);

ALTER TABLE FORNECEDORES ADD COLUMN TELEFONES TEXT; -- Multivalorado

CREATE TABLE IF NOT EXISTS TIPO_DE_ENDERECO (
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENDERECOS (
    NUMERO VARCHAR(10),
    LOGRADOURO VARCHAR(100),
    COMPLEMENTO VARCHAR(50),
    CEP VARCHAR(10),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS (
    NUMERO INT PRIMARY KEY,
    DATA_INCLUSAO DATE,
    VALOR_TOTAL DECIMAL(10, 2),
    VALOR_DESCONTO DECIMAL(10, 2),
    VALOR_LIQUIDO DECIMAL(10, 2),
    ID_FORMA_PAGAMENTO INT,
    QUANTIDADE_PARCELAS INT
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    COR VARCHAR(50),
    DIMENSOES VARCHAR(50),
    PESO DECIMAL(10, 2),
    PRECO DECIMAL(10, 2),
    TEMPO_FABRICACAO TIME,
    DESENHO_DO_PRODUTO TEXT,
    HORAS_MAO_DE_OBRA DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS TIPOS_DE_COMPONENTE (
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPONENTES (
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    QUANTIDADE_EM_ESTOQUE INT,
    PRECO_UNITARIO DECIMAL(10, 2),
    UNIDADE VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS MAQUINAS (
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    TEMPO_DE_VIDA INT,
    DATA_COMPRA DATE,
    DATA_FIM_GARANTIA DATE
);

CREATE TABLE IF NOT EXISTS RE (
    CODIGO INT PRIMARY KEY,
    QUANTIDADE_NECESSARIA INT,
    UNIDADE VARCHAR(10),
    TEMPO_USO TIME,
    HORAS_MAO_DE_OBRA DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS RM (
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    DATA DATE,
    DESCRICAO TEXT
);

CREATE TABLE IF NOT EXISTS RS (
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    QUANTIDADE INT,
    DATA_NECESSIDADE DATE
);

DROP TABLE IF EXISTS RS;
DROP TABLE IF EXISTS RM;
DROP TABLE IF EXISTS RE;
DROP TABLE IF EXISTS MAQUINAS;
DROP TABLE IF EXISTS COMPONENTES;
DROP TABLE IF EXISTS TIPOS_DE_COMPONENTE;
DROP TABLE IF EXISTS PRODUTOS;
DROP TABLE IF EXISTS ENCOMENDAS;
DROP TABLE IF EXISTS ENDERECOS;
DROP TABLE IF EXISTS TIPO_DE_ENDERECO;
DROP TABLE IF EXISTS FORNECEDORES;
DROP TABLE IF EXISTS EMPRESAS;
DROP TABLE IF EXISTS EMPREGADOS;
DROP TABLE IF EXISTS CLIENTES;

