DROP SCHEMA IF EXISTS Inova_Tech;

CREATE SCHEMA Inova_Tech;

USE Inova_Tech;

CREATE TABLE IF NOT EXISTS CLIENTES (
    CLIENTE_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE,
    ENDERECO TEXT,
    STATUS_FIDELIDADE ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO'
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
    FORNECEDOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CONTATO VARCHAR(100),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    PRODUTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(50),
    PRECO DECIMAL(10, 2) NOT NULL,
    ESTOQUE INT DEFAULT 0,
    FORNECEDOR_ID INT,
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID)
);

CREATE TABLE IF NOT EXISTS VENDAS (
    VENDA_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INT,
    DATA_VENDA DATE,
    VALOR_TOTAL DECIMAL(10, 2),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    PAGAMENTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENDA_ID INT,
    DATA_PAGAMENTO DATE,
    VALOR DECIMAL(10, 2),
    STATUS ENUM('PAGO', 'PENDENTE') DEFAULT 'PENDENTE',
    CONSTRAINT FK_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID)
);

ALTER TABLE CLIENTES ADD COLUMN PONTOS_FIDELIDADE INT DEFAULT 0;

DROP TABLE IF EXISTS PAGAMENTOS;
DROP TABLE IF EXISTS VENDAS;
DROP TABLE IF EXISTS PRODUTOS;
DROP TABLE IF EXISTS FORNECEDORES;
DROP TABLE IF EXISTS CLIENTES;

