-- Dropar o esquema se ele já existir
DROP SCHEMA IF EXISTS Estudo_de_casos_1;

-- Criar um novo esquema
CREATE SCHEMA Estudo_de_casos_1;

-- Usar o novo esquema
USE Estudo_de_casos_1;

-- Criar a tabela FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES (
    FORNECEDORES_COD INT PRIMARY KEY,
    FORNECEDORES_NOME VARCHAR(45),
    FORNECEDORES_RUA VARCHAR(45),
    FORNECEDORES_NUMRUA INT,
    FORNECEDORES_BAIRRO VARCHAR(45),
    FORNECEDORES_CIDADE VARCHAR(45),
    FORNECEDORES_ESTADO VARCHAR(45),
    FORNECEDORES_PAIS VARCHAR(30),
    FORNECEDORES_CODPOSTAL VARCHAR(10),
    FORNECEDORES_TELEFONE VARCHAR(15),
    FORNECEDORES_CONTATO TEXT
);

-- Modificações na tabela FORNECEDORES
ALTER TABLE FORNECEDORES ADD COLUMN FORNECEDORES_EMAIL VARCHAR(50);
ALTER TABLE FORNECEDORES DROP COLUMN FORNECEDORES_EMAIL;
ALTER TABLE FORNECEDORES MODIFY FORNECEDORES_TELEFONE VARCHAR(20);
ALTER TABLE FORNECEDORES CHANGE FORNECEDORES_CONTATO FORNECEDORES_OBSERVACOES TEXT;

-- Criar a tabela PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS (
    PRODUTOS_COD INT PRIMARY KEY,
    PRODUTOS_NOME VARCHAR(50),
    PRODUTOS_DESCRICAO TEXT,
    PRODUTOS_ESPECTEC TEXT,
    PRODUTOS_QUANT DECIMAL(10,3),
    PRODUTOS_PRECOUNIT DECIMAL(10,2),
    PRODUTOS_UNIDADEMEDIDA VARCHAR(10),
    PRODUTOS_ESTOQ_MIN DECIMAL(10,3)
);

-- Modificações na tabela PRODUTOS
ALTER TABLE PRODUTOS ADD COLUMN PRODUTOS_PESO DECIMAL(10,2);
ALTER TABLE PRODUTOS DROP COLUMN PRODUTOS_PESO;
ALTER TABLE PRODUTOS MODIFY PRODUTOS_QUANT DECIMAL(12,3);
ALTER TABLE PRODUTOS CHANGE PRODUTOS_ESPECTEC PRODUTOS_ESPECIFICACOES TEXT;

-- Criar a tabela FILIAIS
CREATE TABLE IF NOT EXISTS FILIAIS (
    FILIAIS_COD INT PRIMARY KEY,
    FILIAIS_NOME VARCHAR(30),
    FILIAIS_RUA VARCHAR(100),
    FILIAIS_NUMRUA INT,
    FILIAIS_BAIRRO VARCHAR(50),
    FILIAIS_CIDADE VARCHAR(50),
    FILIAIS_ESTADO VARCHAR(50),
    FILIAIS_PAIS VARCHAR(50),
    FILIAIS_CODPOSTAL VARCHAR(10),
    FILIAIS_CAPACIDADE TEXT
);

-- Modificações na tabela FILIAIS
ALTER TABLE FILIAIS ADD COLUMN FILIAIS_GERENTE VARCHAR(50);
ALTER TABLE FILIAIS DROP COLUMN FILIAIS_GERENTE;
ALTER TABLE FILIAIS MODIFY FILIAIS_CAPACIDADE TEXT;
ALTER TABLE FILIAIS CHANGE FILIAIS_CAPACIDADE FILIAIS_CAPACIDADE_TOTAL TEXT;

-- Criar a tabela PEDIDOS
CREATE TABLE IF NOT EXISTS PEDIDOS (
    PEDIDOS_COD INT PRIMARY KEY,
    PEDIDOS_DATA DATE,
    PEDIDOS_HORA TIME,
    PEDIDOS_PREVISAO DATE,
    PEDIDOS_STATUS VARCHAR(20),
    FORNECEDORES_FORNECEDORES_COD INT,
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (FORNECEDORES_FORNECEDORES_COD) REFERENCES FORNECEDORES(FORNECEDORES_COD)
);

-- Modificações na tabela PEDIDOS
ALTER TABLE PEDIDOS ADD COLUMN PEDIDOS_NOTAS TEXT;
ALTER TABLE PEDIDOS DROP COLUMN PEDIDOS_NOTAS;
ALTER TABLE PEDIDOS MODIFY PEDIDOS_STATUS ENUM('PENDENTE', 'CONCLUIDO', 'EM ESPERA');
ALTER TABLE PEDIDOS CHANGE PEDIDOS_PREVISAO PEDIDOS_DATA_PREVISAO DATE;

-- Criar a tabela RECEBIMENTOS
CREATE TABLE IF NOT EXISTS RECEBIMENTOS (
    RECEBIMENTOS_DATA DATE,
    RECEBIMENTOS_HORA TIME,
    RECEBIMENTOS_QUANT_PROD DECIMAL(10,3),
    RECEBIMENTOS_CONDICAO TEXT,
    PEDIDOS_PEDIDOS_COD INT,
    PRIMARY KEY (PEDIDOS_PEDIDOS_COD),
    CONSTRAINT FK_PEDIDOS FOREIGN KEY (PEDIDOS_PEDIDOS_COD) REFERENCES PEDIDOS(PEDIDOS_COD)
);

-- Modificações na tabela RECEBIMENTOS
ALTER TABLE RECEBIMENTOS ADD COLUMN RECEBIMENTOS_STATUS VARCHAR(20);
ALTER TABLE RECEBIMENTOS DROP COLUMN RECEBIMENTOS_STATUS;
ALTER TABLE RECEBIMENTOS MODIFY RECEBIMENTOS_QUANT_PROD DECIMAL(12,3);
ALTER TABLE RECEBIMENTOS CHANGE RECEBIMENTOS_CONDICAO RECEBIMENTOS_ESTADO TEXT;

-- Criar a tabela PEDIDOS_PRODUTOS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS (
    PEDIDOS_PEDIDOS_COD INT,
    PRODUTOS_PRODUTOS_COD INT,
    PEDIDOS_PRODUTOS_QUANT DECIMAL(10,3),
    PRIMARY KEY (PEDIDOS_PEDIDOS_COD, PRODUTOS_PRODUTOS_COD),
    CONSTRAINT FK_PEDIDOS_PROD FOREIGN KEY (PEDIDOS_PEDIDOS_COD) REFERENCES PEDIDOS(PEDIDOS_COD),
    CONSTRAINT FK_PRODUTOS_PROD FOREIGN KEY (PRODUTOS_PRODUTOS_COD) REFERENCES PRODUTOS(PRODUTOS_COD)
);

-- Modificações na tabela PEDIDOS_PRODUTOS
ALTER TABLE PEDIDOS_PRODUTOS ADD COLUMN PEDIDOS_PRODUTOS_DESCONTO DECIMAL(5,2);
ALTER TABLE PEDIDOS_PRODUTOS DROP COLUMN PEDIDOS_PRODUTOS_DESCONTO;
ALTER TABLE PEDIDOS_PRODUTOS MODIFY PEDIDOS_PRODUTOS_QUANT DECIMAL(12,3);
ALTER TABLE PEDIDOS_PRODUTOS CHANGE PEDIDOS_PRODUTOS_QUANT PEDIDOS_PRODUTOS_QUANTIDADE DECIMAL(10,3);

-- Criar a tabela FILIAIS_PRODUTOS
CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS (
    FILIAIS_FILIAIS_COD INT,
    PRODUTOS_PRODUTOS_COD INT,
    FILIAIS_PRODUTOS_QUANT DECIMAL(10,3),
    PRIMARY KEY (FILIAIS_FILIAIS_COD, PRODUTOS_PRODUTOS_COD),
    CONSTRAINT FK_FILIAIS FOREIGN KEY (FILIAIS_FILIAIS_COD) REFERENCES FILIAIS(FILIAIS_COD),
    CONSTRAINT FK_PRODUTOS_FIL FOREIGN KEY (PRODUTOS_PRODUTOS_COD) REFERENCES PRODUTOS(PRODUTOS_COD)
);

-- Modificações na tabela FILIAIS_PRODUTOS
ALTER TABLE FILIAIS_PRODUTOS ADD COLUMN FILIAIS_PRODUTOS_PRECO DECIMAL(10,2);
ALTER TABLE FILIAIS_PRODUTOS DROP COLUMN FILIAIS_PRODUTOS_PRECO;
ALTER TABLE FILIAIS_PRODUTOS MODIFY FILIAIS_PRODUTOS_QUANT DECIMAL(12,3);
ALTER TABLE FILIAIS_PRODUTOS CHANGE FILIAIS_PRODUTOS_QUANT FILIAIS_PRODUTOS_QUANTIDADE DECIMAL(10,3);

-- Criar a tabela FORNECEDORES_PRODUTOS
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS (
    FORNECEDORES_FORNECEDORES_COD INT,
    PRODUTOS_PRODUTOS_COD INT,
    PRIMARY KEY (FORNECEDORES_FORNECEDORES_COD, PRODUTOS_PRODUTOS_COD),
    CONSTRAINT FK_FORNECEDORES FOREIGN KEY (FORNECEDORES_FORNECEDORES_COD) REFERENCES FORNECEDORES(FORNECEDORES_COD),
    CONSTRAINT FK_PRODUTOS_FORN FOREIGN KEY (PRODUTOS_PRODUTOS_COD) REFERENCES PRODUTOS(PRODUTOS_COD)
);

-- Modificações na tabela FORNECEDORES_PRODUTOS
ALTER TABLE FORNECEDORES_PRODUTOS ADD COLUMN FORNECEDORES_PRODUTOS_PRAZO_ENTREGA INT;
ALTER TABLE FORNECEDORES_PRODUTOS DROP COLUMN FORNECEDORES_PRODUTOS_PRAZO_ENTREGA;
ALTER TABLE FORNECEDORES_PRODUTOS MODIFY FORNECEDORES_FORNECEDORES_COD INT;
ALTER TABLE FORNECEDORES_PRODUTOS CHANGE FORNECEDORES_FORNECEDORES_COD FORNECEDORES_ID INT;

-- Dropar as tabelas (se necessário, para manutenção)
-- DROP TABLE IF EXISTS FORNECEDORES_PRODUTOS;
-- DROP TABLE IF EXISTS FILIAIS_PRODUTOS;
-- DROP TABLE IF EXISTS PEDIDOS_PRODUTOS;
-- DROP TABLE IF EXISTS RECEBIMENTOS;
-- DROP TABLE IF EXISTS PEDIDOS;
-- DROP TABLE IF EXISTS FILIAIS;
-- DROP TABLE IF EXISTS PRODUTOS;
-- DROP TABLE IF EXISTS FORNECEDORES;
