DROP SCHEMA IF EXISTS Estudo_de_casos_2;

CREATE SCHEMA Estudo_de_casos_2;

USE Estudo_de_casos_2;

CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASSAGEIRO_COD INT PRIMARY KEY,
    PASSAGEIRO_NOME VARCHAR(100) NOT NULL,
    PASSAGEIRO_CPF VARCHAR(11) NOT NULL UNIQUE,
    PASSAGEIRO_TELEFONE VARCHAR(20),
    PASSAGEIRO_RESIDENCIA TEXT
);

ALTER TABLE PASSAGEIROS ADD COLUMN PASSAGEIRO_EMAIL VARCHAR(100);
ALTER TABLE PASSAGEIROS DROP COLUMN PASSAGEIRO_EMAIL;
ALTER TABLE PASSAGEIROS MODIFY PASSAGEIRO_TELEFONE VARCHAR(25);
ALTER TABLE PASSAGEIROS CHANGE PASSAGEIRO_RESIDENCIA PASSAGEIRO_ENDERECO TEXT;

CREATE TABLE IF NOT EXISTS AEROPORTOS (
    AEROPORTO_COD INT PRIMARY KEY,
    AEROPORTO_NOME VARCHAR(50) NOT NULL,
    AEROPORTO_CIDADE VARCHAR(100),
    AEROPORTO_REGIAO VARCHAR(50)
);

ALTER TABLE AEROPORTOS ADD COLUMN AEROPORTO_TELEFONE VARCHAR(20);
ALTER TABLE AEROPORTOS DROP COLUMN AEROPORTO_TELEFONE;
ALTER TABLE AEROPORTOS MODIFY AEROPORTO_NOME VARCHAR(100);
ALTER TABLE AEROPORTOS CHANGE AEROPORTO_REGIAO AEROPORTO_ZONA VARCHAR(50);

CREATE TABLE IF NOT EXISTS AERONAVES (
    AERONAVE_COD INT PRIMARY KEY,
    AERONAVE_TIPO VARCHAR(50) NOT NULL,
    AERONAVE_CAPACIDADE INT
);

ALTER TABLE AERONAVES ADD COLUMN AERONAVE_MODELO VARCHAR(50);
ALTER TABLE AERONAVES DROP COLUMN AERONAVE_MODELO;
ALTER TABLE AERONAVES MODIFY AERONAVE_CAPACIDADE INT;

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    FUNCIONARIO_COD INT PRIMARY KEY,
    FUNCIONARIO_NOME VARCHAR(100) NOT NULL,
    FUNCIONARIO_FUNCAO VARCHAR(50)
);

ALTER TABLE FUNCIONARIOS ADD COLUMN FUNCIONARIO_EMAIL VARCHAR(100);
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNCIONARIO_EMAIL;
ALTER TABLE FUNCIONARIOS MODIFY FUNCIONARIO_FUNCAO VARCHAR(70);

CREATE TABLE IF NOT EXISTS VOOS (
    VOO_COD INT PRIMARY KEY,
    VOO_ORIGEM INT NOT NULL,
    VOO_DESTINO INT NOT NULL,
    VOO_PARTIDA TIME,
    VOO_HORA_CHEGADA TIME,
    AERONAVE_COD INT,
    CONSTRAINT FK_VOO_ORIGEM FOREIGN KEY (VOO_ORIGEM) REFERENCES AEROPORTOS(AEROPORTO_COD),
    CONSTRAINT FK_VOO_DESTINO FOREIGN KEY (VOO_DESTINO) REFERENCES AEROPORTOS(AEROPORTO_COD),
    CONSTRAINT FK_AERONAVE FOREIGN KEY (AERONAVE_COD) REFERENCES AERONAVES(AERONAVE_COD)
);

ALTER TABLE VOOS ADD COLUMN VOO_STATUS VARCHAR(20);
ALTER TABLE VOOS DROP COLUMN VOO_STATUS;
ALTER TABLE VOOS MODIFY VOO_PARTIDA TIME;

CREATE TABLE IF NOT EXISTS RESERVAS (
    RESERVA_COD INT PRIMARY KEY,
    PASSAGEIRO_COD INT,
    VOO_COD INT,
    RESERVA_DATA_HORA DATE,
    CONSTRAINT FK_PASSAGEIRO FOREIGN KEY (PASSAGEIRO_COD) REFERENCES PASSAGEIROS(PASSAGEIRO_COD),
    CONSTRAINT FK_VOO FOREIGN KEY (VOO_COD) REFERENCES VOOS(VOO_COD)
);

ALTER TABLE RESERVAS ADD COLUMN RESERVA_NOTAS TEXT;
ALTER TABLE RESERVAS DROP COLUMN RESERVA_NOTAS;

CREATE TABLE IF NOT EXISTS OPERACOES_VOO (
    VOO_COD INT,
    FUNCIONARIO_COD INT,
    PRIMARY KEY (VOO_COD, FUNCIONARIO_COD),
    CONSTRAINT FK_VOO_OP FOREIGN KEY (VOO_COD) REFERENCES VOOS(VOO_COD),
    CONSTRAINT FK_FUNC_OP FOREIGN KEY (FUNCIONARIO_COD) REFERENCES FUNCIONARIOS(FUNCIONARIO_COD)
);

ALTER TABLE OPERACOES_VOO ADD COLUMN OPERACAO_DATA DATE;
ALTER TABLE OPERACOES_VOO DROP COLUMN OPERACAO_DATA;

DROP TABLE IF EXISTS OPERACOES_VOO;
DROP TABLE IF EXISTS RESERVAS;
DROP TABLE IF EXISTS VOOS;
DROP TABLE IF EXISTS FUNCIONARIOS;
DROP TABLE IF EXISTS AERONAVES;
DROP TABLE IF EXISTS AEROPORTOS;
DROP TABLE IF EXISTS PASSAGEIROS;

